// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tot.Infrastructure.Persistence;

#nullable disable

namespace Tot.Infrastructure.Migrations
{
    [DbContext(typeof(TotPostgreSqlDbContext))]
    [Migration("20251107012602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tot.Domain.Entities.Question.QuestionPool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendlyUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionFormatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QuestionPoolCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UseLastAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("QuestionPoolCategoryId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("QuestionPools", "Question");
                });

            modelBuilder.Entity("Tot.Domain.Entities.Question.QuestionPoolCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("QuestionPoolCategories", "Question");
                });

            modelBuilder.Entity("Tot.Domain.Entities.Question.QuestionPoolItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<int>("QuestionPoolId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VoteCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionPoolId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("QuestionPoolItems", "Question");
                });

            modelBuilder.Entity("Tot.Domain.Entities.Question.QuestionPool", b =>
                {
                    b.HasOne("Tot.Domain.Entities.Question.QuestionPoolCategory", "QuestionPoolCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tot.Domain.Entities.Question.QuestionPoolCategory", null)
                        .WithMany("Items")
                        .HasForeignKey("QuestionPoolCategoryId");

                    b.Navigation("QuestionPoolCategory");
                });

            modelBuilder.Entity("Tot.Domain.Entities.Question.QuestionPoolItem", b =>
                {
                    b.HasOne("Tot.Domain.Entities.Question.QuestionPool", null)
                        .WithMany("Items")
                        .HasForeignKey("QuestionPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tot.Domain.Entities.Question.QuestionPool", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tot.Domain.Entities.Question.QuestionPoolCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
